# Generated by Django 3.2.12 on 2022-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
