# Generated by Django 3.2.12 on 2022-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='is_active_matricula',
            field=models.BooleanField(default=True),
        ),
    ]
