# Generated by Django 3.2.12 on 2022-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_periodo_is_active_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
