# Generated by Django 3.2.12 on 2022-10-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_area_cargo_cargoarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoarea',
            name='grado_academico',
            field=models.CharField(blank=True, choices=[('Lic.', 'Licenciado'), ('Ing.', 'Ingeniero'), ('Mrto.', 'Maestro'), ('Dr.', 'Doctorado')], max_length=50, null=True),
        ),
    ]
