# Generated by Django 3.2.12 on 2022-12-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cargoarea_grado_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoarea',
            name='grado_academico',
            field=models.CharField(blank=True, choices=[('Bach.', 'Bachiller'), ('Lic.', 'Licenciado'), ('Ing.', 'Ingeniero'), ('Mtro.', 'Maestro'), ('Dr.', 'Doctorado')], max_length=50, null=True),
        ),
    ]
