# Generated by Django 3.2.12 on 2023-01-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0028_auto_20221215_1226'),
        ('core', '0011_alter_cargoarea_grado_academico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descipcion', models.CharField(max_length=250)),
                ('promocion', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicos.programa')),
            ],
        ),
    ]
