# Generated by Django 3.2.12 on 2023-04-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='fecha_extemporaneo_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='fecha_extemporaneo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
