# Generated by Django 3.2.12 on 2023-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230518_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoarea',
            name='grado_academico',
            field=models.CharField(blank=True, choices=[('Bach.', 'Bachiller'), ('Lic.', 'Licenciado'), ('Ing.', 'Ingeniero'), ('Mtro.', 'Maestro'), ('Dr.', 'Doctorado'), ('C.P.C.', 'Contador Público')], max_length=50, null=True),
        ),
    ]
