# Generated by Django 3.2.12 on 2023-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cargoarea_grado_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='is_active_matricula',
            field=models.BooleanField(default=True),
        ),
    ]
