# Generated by Django 3.2.12 on 2024-01-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_etapa_is_active_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'headquarter',
                'verbose_name_plural': 'headquarters',
            },
        ),
        migrations.AlterField(
            model_name='cargoarea',
            name='headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.headquarter'),
        ),
    ]
