# Generated by Django 3.2.12 on 2024-01-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240122_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='charge_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
