# Generated by Django 3.2.12 on 2024-02-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_persona_juridica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoarea',
            name='area',
        ),
        migrations.AddField(
            model_name='cargoarea',
            name='area',
            field=models.ManyToManyField(to='core.Area'),
        ),
    ]
