# Generated by Django 3.2.12 on 2024-02-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240208_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='persona_juridica',
            new_name='PersonaJuridica',
        ),
    ]
