# Generated by Django 3.2.12 on 2024-02-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_persona_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajuridica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
