# Generated by Django 3.2.12 on 2024-03-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20240215_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='charge_number',
        ),
    ]
