# Generated by Django 3.2.12 on 2024-03-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_area_charge_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
