# Generated by Django 3.2.12 on 2022-03-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0002_auto_20220330_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
