# Generated by Django 3.2.12 on 2022-04-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0003_alter_programa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
