# Generated by Django 3.2.12 on 2022-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0004_programa_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='cuotas',
            field=models.IntegerField(default=1),
        ),
    ]
