# Generated by Django 3.2.12 on 2022-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0005_programa_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprograma',
            name='cantidad_matriculas',
            field=models.IntegerField(default=0),
        ),
    ]
