# Generated by Django 3.2.12 on 2022-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0007_auto_20220519_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='limite_registros',
            field=models.IntegerField(default=0),
        ),
    ]
