# Generated by Django 3.2.12 on 2022-05-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0008_auto_20220519_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='horario',
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='academicos.cursos'),
            preserve_default=False,
        ),
    ]
