# Generated by Django 3.2.12 on 2022-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0009_auto_20220520_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
