# Generated by Django 3.2.12 on 2022-05-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0010_cursos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicos.docente'),
        ),
    ]
