# Generated by Django 3.2.12 on 2022-05-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_persona_user'),
        ('academicos', '0011_alter_horario_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.periodo'),
            preserve_default=False,
        ),
    ]
