# Generated by Django 3.2.12 on 2022-05-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0012_matricula_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='horarios',
            field=models.ManyToManyField(to='academicos.Horario'),
        ),
    ]
