# Generated by Django 3.2.12 on 2022-05-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0013_matricula_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='horarios',
            field=models.ManyToManyField(blank=True, null=True, to='academicos.Horario'),
        ),
    ]
