# Generated by Django 3.2.12 on 2022-05-20 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_persona_user'),
        ('academicos', '0014_alter_matricula_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='limite_registros',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='periodo',
        ),
        migrations.CreateModel(
            name='CursoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50)),
                ('limite_registros', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicos.cursos')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicos.docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='grupo_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicos.cursogrupo'),
        ),
    ]
