# Generated by Django 3.2.12 on 2022-05-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0015_auto_20220520_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='grupo_curso',
            new_name='curso_grupo',
        ),
    ]
