# Generated by Django 3.2.12 on 2022-05-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0016_rename_grupo_curso_horario_curso_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='horarios',
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicos.cursogrupo'),
        ),
    ]
