# Generated by Django 3.2.12 on 2022-06-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0017_auto_20220520_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='is_cerrado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='is_publicado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='promedio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
