# Generated by Django 3.2.12 on 2022-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0018_auto_20220630_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='promedio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
