# Generated by Django 3.2.12 on 2022-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0019_alter_matricula_promedio_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursogrupo',
            name='fecha_inico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursogrupo',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursogrupo',
            name='resolucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
