# Generated by Django 3.2.12 on 2022-07-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0020_auto_20220714_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursogrupo',
            old_name='fecha_inico',
            new_name='fecha_inicio',
        ),
    ]
