# Generated by Django 3.2.12 on 2022-09-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0022_matricula_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='is_retirado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
