# Generated by Django 3.2.12 on 2022-09-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0023_matricula_is_retirado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='is_cerrado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='is_publicado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='is_retirado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
