# Generated by Django 3.2.12 on 2022-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0024_auto_20220907_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='is_cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='is_publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='is_retirado',
            field=models.BooleanField(default=False),
        ),
    ]
