# Generated by Django 3.2.12 on 2022-11-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0025_auto_20220907_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursogrupo',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
