# Generated by Django 3.2.12 on 2022-11-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0026_auto_20221107_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_set', to='academicos.cursos')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisito_set', to='academicos.cursos')),
            ],
        ),
    ]
