# Generated by Django 3.2.12 on 2022-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0027_requisitocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='fecha_cierre_acta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='fecha_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
