# Generated by Django 3.2.12 on 2023-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0028_auto_20221215_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='fecha_aplazado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='is_aplazado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matricula',
            name='obs_aplazado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='promedio_final_aplazado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
