# Generated by Django 3.2.12 on 2023-05-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0029_auto_20230208_1129'),
    ]

    operations = [
    ]
