# Generated by Django 3.2.12 on 2023-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0029_auto_20230208_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='is_dirigido',
            field=models.BooleanField(default=False),
        ),
    ]
