# Generated by Django 3.2.12 on 2023-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0030_matricula_is_dirigido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursogrupo',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('DI', 'DI')], max_length=50),
        ),
    ]
