# Generated by Django 3.2.12 on 2023-05-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0031_alter_cursogrupo_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplazado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('modalidad', models.CharField(choices=[('P', 'PRESENCIAL'), ('V', 'VIRTUAL')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicos.docente')),
            ],
        ),
    ]
