# Generated by Django 3.2.12 on 2023-06-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0030_merge_0029_auto_20230208_1129_0029_auto_20230504_1232'),
        ('academicos', '0032_aplazado'),
    ]

    operations = [
    ]
