# Generated by Django 3.2.12 on 2023-06-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0033_merge_20230616_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='obs_aplazado',
            new_name='observacion',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='fecha_aplazado',
        ),
        migrations.RemoveField(
            model_name='tipoprograma',
            name='cantidad_matriculas',
        ),
        migrations.AddField(
            model_name='aplazado',
            name='is_cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aplazado',
            name='is_publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aplazado',
            name='num_acta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aplazado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicos.aplazado'),
        ),
        migrations.AddField(
            model_name='programa',
            name='cantidad_matriculas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aplazado',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
