# Generated by Django 3.2.12 on 2023-09-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0034_auto_20230616_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='is_convalidado',
            field=models.BooleanField(default=False),
        ),
    ]
