# Generated by Django 3.2.12 on 2023-11-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academicos", "0036_auto_20231017_1128"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsistenciaDocente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True, null=True)),
                ("hora_ingreso", models.TimeField(blank=True, null=True)),
                ("hora_salida", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cursogrupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academicos.cursogrupo",
                    ),
                ),
            ],
        ),
    ]
