# Generated by Django 3.2.12 on 2023-12-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academicos", "0037_asistenciadocente"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="num_acta_ref",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
