# Generated by Django 3.2.12 on 2023-12-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0037_asistenciadocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='num_acta_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
