# Generated by Django 3.2.12 on 2023-12-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0038_matricula_num_acta_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
