# Generated by Django 3.2.12 on 2024-01-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0039_matricula_is_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planestudio',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicos.programa'),
        ),
    ]
