# Generated by Django 3.2.12 on 2022-05-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_periodo'),
        ('accounts', '0004_auto_20220412_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
    ]
