# Generated by Django 3.2.12 on 2022-05-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usermodel_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
