# Generated by Django 3.2.12 on 2022-03-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='fecha',
            new_name='fecha_operacion',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='concepto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concepto',
            name='programa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_documento',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
