# Generated by Django 3.2.12 on 2022-03-30 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0001_initial'),
        ('economicos', '0002_auto_20220330_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academicos.programa'),
            preserve_default=False,
        ),
    ]
