# Generated by Django 3.2.12 on 2022-03-30 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicos', '0001_initial'),
        ('economicos', '0003_alter_concepto_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicos.programa'),
        ),
    ]
