# Generated by Django 3.2.12 on 2022-04-21 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0001_initial'),
        ('economicos', '0004_alter_concepto_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='expendiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admision.expediente'),
        ),
    ]
