# Generated by Django 3.2.12 on 2022-04-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economicos', '0005_pago_expendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='is_conciliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_conciliacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
