# Generated by Django 3.2.12 on 2022-06-30 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economicos', '0006_auto_20220421_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryImporBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrebatch', models.CharField(max_length=70)),
                ('fecha', models.DateField()),
                ('fechaingreso', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
