# Generated by Django 3.2.12 on 2022-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economicos', '0007_historyimporbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='adjunto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
