# Generated by Django 3.2.12 on 2022-07-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economicos', '0008_pago_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos'),
        ),
    ]
