# Generated by Django 3.2.12 on 2022-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economicos', '0009_alter_pago_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='is_validado',
            field=models.BooleanField(default=False),
        ),
    ]
