from django.urls import include, path

from desk.router import router
from desk.views import (
    generete_code_hash,
    get_procedure_and_tracing_by_id,
    get_dashboard_procedures,
    get_tracings_procedures,
    update_procedure,
    years_for_procedures,
    save_derive_procedure,
    approve_tracing,
    get_areas,
    get_user_for_area,
    finally_procedure,
    get_procedures_requirements,
    get_user_profile,
    # new views
    login,
    get_procedures,
    get_procedures_in_started,
    get_procedures_for_user,
    get_procedures_in_assigned,
    save_procedure,
    get_procedure_by_id,
    get_tracings_to_approved_for_area,
    get_tracings_to_approved_for_user,
    get_procedures_finished,
    archive_procedure,
    anexar_procedure,
    get_procedures_charges,
    get_procedures_derivations,
    create_procedure_charge,
    get_procedures_reports,
    get_procedure_and_tracing_by_code_number,
    save_procedure_externo,
)

urlpatterns = [
    path("", include(router.urls)),
    path("generete_code_hash", generete_code_hash),
    # new paths
    path("login/", login, name="login"),
    path("get_procedures", get_procedures, name="get_procedures"),
    path(
        "get_procedures_in_started",
        get_procedures_in_started,
        name="get_procedures_in_started",
    ),
    path(
        "get_procedures_in_assigned",
        get_procedures_in_assigned,
        name="get_procedures_in_assigned",
    ),
    path(
        "get_procedures_for_user",
        get_procedures_for_user,
        name="get_procedures_for_user",
    ),
    path("get_procedure_by_id/<int:procedure_id>", get_procedure_by_id),
    path("get_procedure_and_tracing_by_id", get_procedure_and_tracing_by_id),
    path("get_user_for_area", get_user_for_area, name="get_user_for_area"),
    path("save_procedure", save_procedure, name="save_procedure"),
    path("update_procedure", update_procedure),
    path("save_derive_procedure", save_derive_procedure),
    path(
        "finally_procedure",
        finally_procedure,
        name="finally_procedure",
    ),
    path("get_tracings_to_approved_for_area", get_tracings_to_approved_for_area),
    path("get_tracings_to_approved_for_user", get_tracings_to_approved_for_user),
    path("approve_tracing", approve_tracing, name="approve_tracing"),
    path("get_procedures_finished", get_procedures_finished),
    path("archive_procedure", archive_procedure),
    path("anexar_procedure", anexar_procedure),
    path("get_procedures_charges", get_procedures_charges),
    path("get_procedures_derivations", get_procedures_derivations),
    path("create_procedure_charge", create_procedure_charge),
    path("get_procedures_reports", get_procedures_reports),
    path(
        "get_procedure_and_tracing_by_code_number",
        get_procedure_and_tracing_by_code_number,
    ),
    path("save_procedure_externo", save_procedure_externo),
    # OLD
    path("get_tracings_procedures/<int:status>", get_tracings_procedures),
    path("get_dashboard_procedures", get_dashboard_procedures),
    path("years_for_procedures", years_for_procedures),
    path("get_areas", get_areas, name="get_areas"),
    path(
        "get_procedures_requirements",
        get_procedures_requirements,
        name="get_procedures_requirements",
    ),
    path("get_user_profile", get_user_profile, name="get_user_profile"),
]
