# Generated by Django 3.2.12 on 2023-01-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_etapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'headquarter',
                'verbose_name_plural': 'headquarters',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.TextField()),
                ('reference_doc_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.file')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.headquarter')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
            options={
                'verbose_name': 'procedure',
                'verbose_name_plural': 'procedures',
            },
        ),
        migrations.CreateModel(
            name='ProcedureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'procedure requirement',
                'verbose_name_plural': 'procedure requirements',
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'procedure type',
                'verbose_name_plural': 'procedure types',
            },
        ),
        migrations.CreateModel(
            name='ProcedureTracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('is_started', models.BooleanField(default=False)),
                ('is_revision', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.procedure')),
                ('referral_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
            ],
            options={
                'verbose_name': 'procedure tracing',
                'verbose_name_plural': 'procedure tracings',
            },
        ),
        migrations.CreateModel(
            name='Procedure_ProcedureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.proceduretype')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.procedurerequirement')),
            ],
            options={
                'verbose_name': 'procedure_procedurerequirement',
                'verbose_name_plural': 'procedure_procedurerequirements',
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.proceduretype'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
