# Generated by Django 3.2.12 on 2023-03-13 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_auto_20230313_0900'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'headquarter',
                'verbose_name_plural': 'headquarters',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.TextField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='procedures/attached_files/')),
                ('reference_doc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.file')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.headquarter')),
            ],
            options={
                'verbose_name': 'procedure',
                'verbose_name_plural': 'procedures',
            },
        ),
        migrations.CreateModel(
            name='ProcedureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'procedure requirement',
                'verbose_name_plural': 'procedure requirements',
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'procedure type',
                'verbose_name_plural': 'procedure types',
            },
        ),
        migrations.CreateModel(
            name='ProcedureTracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('action_log', models.TextField(blank=True, null=True)),
                ('document_response', models.FileField(blank=True, null=True, upload_to='procedures/document_response/')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('from_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_area', to='core.area')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.procedure')),
                ('ref_procedure_tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_tracking', to='desk.proceduretracing')),
                ('to_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_area', to='core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'procedure tracing',
                'verbose_name_plural': 'procedure tracings',
            },
        ),
        migrations.CreateModel(
            name='Procedure_ProcReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.proceduretype')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.procedurerequirement')),
            ],
            options={
                'verbose_name': 'procedure_procreq',
                'verbose_name_plural': 'procedure_procreqs',
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.proceduretype'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
