# Generated by Django 3.2.12 on 2023-01-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procedure_ProcedureRequirement',
            new_name='Procedure_ProcReq',
        ),
        migrations.AlterModelOptions(
            name='procedure_procreq',
            options={'verbose_name': 'procedure_procreq', 'verbose_name_plural': 'procedure_procreqs'},
        ),
    ]
