# Generated by Django 3.2.12 on 2023-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='reference_doc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
