# Generated by Django 3.2.12 on 2023-04-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230424_1307'),
        ('desk', '0002_file_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretracing',
            name='from_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_area', to='core.area'),
        ),
        migrations.AddField(
            model_name='proceduretracing',
            name='to_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_area', to='core.area'),
        ),
    ]
