# Generated by Django 3.2.12 on 2023-01-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_etapa'),
        ('desk', '0002_auto_20230118_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='person',
        ),
        migrations.RemoveField(
            model_name='proceduretracing',
            name='is_revision',
        ),
        migrations.RemoveField(
            model_name='proceduretracing',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='proceduretracing',
            name='referral_area',
        ),
        migrations.AddField(
            model_name='file',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
        migrations.AddField(
            model_name='procedure_procreq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proceduretracing',
            name='from_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_area', to='core.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proceduretracing',
            name='to_area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='to_area', to='core.area'),
            preserve_default=False,
        ),
    ]
