# Generated by Django 3.2.12 on 2023-05-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_auto_20230424_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='number_of_sheets',
            field=models.IntegerField(default=0),
        ),
    ]
