# Generated by Django 3.2.12 on 2024-01-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economicos', '0010_pago_is_validado'),
        ('core', '0019_auto_20240122_1248'),
        ('desk', '0004_procedure_number_of_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretype',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='economicos.concepto'),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='attached_files',
            field=models.FileField(blank=True, null=True, upload_to='tramites/'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.headquarter'),
        ),
        migrations.DeleteModel(
            name='Headquarter',
        ),
    ]
