# Generated by Django 3.2.12 on 2024-01-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20240125_0842'),
        ('desk', '0005_auto_20240122_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
    ]
