# Generated by Django 3.2.12 on 2024-02-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20240125_0842'),
        ('desk', '0006_file_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='for_the_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_the_area', to='core.area'),
        ),
    ]
