# Generated by Django 3.2.12 on 2024-02-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0007_procedure_for_the_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='reference_doc_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
