# Generated by Django 3.2.12 on 2024-02-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_persona_juridica_personajuridica'),
        ('desk', '0008_alter_procedure_reference_doc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='legalperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personajuridica'),
        ),
    ]
