# Generated by Django 3.2.12 on 2024-02-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0009_file_legalperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduretracing',
            name='document_response',
            field=models.FileField(blank=True, null=True, upload_to='tramites/seguimiento/'),
        ),
    ]
