# Generated by Django 3.2.12 on 2024-02-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0010_alter_proceduretracing_document_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretracing',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
