# Generated by Django 3.2.12 on 2024-02-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0011_proceduretracing_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.procedure')),
                ('procedure_anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_anexo', to='desk.procedure')),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
            },
        ),
    ]
