# Generated by Django 3.2.12 on 2024-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0012_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretracing',
            name='is_anexed',
            field=models.BooleanField(default=False),
        ),
    ]
