# Generated by Django 3.2.12 on 2024-03-04 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_area_charge_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desk', '0013_proceduretracing_is_anexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'procedure charge',
                'verbose_name_plural': 'procedure charges',
            },
        ),
        migrations.AddField(
            model_name='proceduretracing',
            name='procedure_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desk.procedurecharge'),
        ),
    ]
