# Generated by Django 3.2.12 on 2024-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0014_auto_20240304_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurecharge',
            name='correlative',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
