# Generated by Django 3.2.12 on 2024-03-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0015_alter_procedurecharge_correlative'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecharge',
            name='path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
