# Generated by Django 3.2.12 on 2024-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0016_procedurecharge_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurecharge',
            name='path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
