# Generated by Django 3.2.12 on 2024-03-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0017_alter_procedurecharge_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedurecharge',
            old_name='path',
            new_name='path_file',
        ),
    ]
