# Generated by Django 3.2.12 on 2024-03-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0018_rename_path_procedurecharge_path_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurecharge',
            name='area',
        ),
        migrations.RemoveField(
            model_name='procedurecharge',
            name='path_file',
        ),
    ]
