# Generated by Django 3.2.12 on 2024-03-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0019_auto_20240311_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='code_hash',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
