# Generated by Django 3.2.12 on 2024-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0020_procedure_code_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
