# Generated by Django 3.2.12 on 2024-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0022_alter_procedure_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='code_hash',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
