# Generated by Django 3.2.12 on 2024-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0023_alter_procedure_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='attached_files',
            field=models.FileField(blank=True, null=True, upload_to='tramites/adjunto/'),
        ),
    ]
