# Generated by Django 3.2.12 on 2024-04-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0024_alter_procedure_attached_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretracing',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
