# Generated by Django 3.2.12 on 2022-12-20 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_cargoarea_grado_academico'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoTramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_nombre', models.CharField(max_length=30, null=True)),
                ('documento_identidad', models.CharField(max_length=20, null=True)),
                ('asunto', models.TextField()),
                ('documento_referencia', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('sede_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.sede')),
                ('tipo_tramite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.tipotramite')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
