# Generated by Django 3.2.12 on 2022-12-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cargoarea_grado_academico'),
        ('mesa_partes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tramites',
            name='documento_referencia',
        ),
        migrations.RenameModel(
            old_name='TipoTramite',
            new_name='TiposTramites',
        ),
        migrations.CreateModel(
            name='Tramites_Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('requisito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.requisitostramites')),
                ('tipo_tramite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.tipostramites')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientosTramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('is_iniciado', models.BooleanField(default=True)),
                ('is_revision', models.BooleanField(default=False)),
                ('is_concluido', models.BooleanField(default=False)),
                ('area_derivacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('tramite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.tramites')),
            ],
        ),
        migrations.AlterField(
            model_name='tramites',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.sedes'),
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
