# Generated by Django 3.2.12 on 2022-12-20 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cargoarea_grado_academico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mesa_partes', '0002_auto_20221220_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequisitosTramites',
            new_name='RequisitosTramite',
        ),
        migrations.RenameModel(
            old_name='Sedes',
            new_name='Sede',
        ),
        migrations.RenameModel(
            old_name='SeguimientosTramites',
            new_name='SeguimientosTramite',
        ),
        migrations.RenameModel(
            old_name='TiposTramites',
            new_name='TiposTramite',
        ),
        migrations.RenameModel(
            old_name='Tramites',
            new_name='Tramite',
        ),
        migrations.RenameModel(
            old_name='Tramites_Requisitos',
            new_name='Tramites_Requisito',
        ),
    ]
