# Generated by Django 3.2.12 on 2022-12-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cargoarea_grado_academico'),
        ('mesa_partes', '0003_auto_20221220_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequisitosTramite',
            new_name='RequisitoTramite',
        ),
        migrations.RenameModel(
            old_name='SeguimientosTramite',
            new_name='SeguimientoTramite',
        ),
        migrations.RenameModel(
            old_name='TiposTramite',
            new_name='TipoTramite',
        ),
        migrations.RenameModel(
            old_name='Tramites_Requisito',
            new_name='Tramite_Requisito',
        ),
        migrations.AlterModelOptions(
            name='requisitotramite',
            options={'verbose_name_plural': 'Requisitos de los tramites'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='seguimientotramite',
            options={'verbose_name_plural': 'Seguimiento de los Tramites'},
        ),
        migrations.AlterModelOptions(
            name='tipotramite',
            options={'verbose_name_plural': 'Tipos de tramites'},
        ),
        migrations.AlterModelOptions(
            name='tramite',
            options={'verbose_name_plural': 'Tramites'},
        ),
        migrations.AlterModelOptions(
            name='tramite_requisito',
            options={'verbose_name': 'Tramite y requisito', 'verbose_name_plural': 'Tramites y requisitos'},
        ),
    ]
