# Generated by Django 3.2.12 on 2022-12-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cargoarea_grado_academico'),
        ('mesa_partes', '0004_auto_20221220_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitotramite',
            options={'verbose_name': 'requisito de tramite', 'verbose_name_plural': 'requisitos de los tramites'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name_plural': 'sedes'},
        ),
        migrations.AlterModelOptions(
            name='tipotramite',
            options={'verbose_name': 'tipo de tramite', 'verbose_name_plural': 'tipos de tramites'},
        ),
        migrations.AlterModelOptions(
            name='tramite',
            options={'verbose_name': 'tramite', 'verbose_name_plural': 'tramites'},
        ),
        migrations.RenameField(
            model_name='tramite',
            old_name='sede_id',
            new_name='sede',
        ),
        migrations.RenameField(
            model_name='tramite',
            old_name='tipo_tramite_id',
            new_name='tipo de tramite',
        ),
        migrations.RenameField(
            model_name='tramite',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='tipotramite',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='persona_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='persona_nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
