# Generated by Django 3.2.12 on 2022-12-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0005_auto_20221220_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramite_requisito',
            options={'verbose_name': 'tramite y requisito', 'verbose_name_plural': 'tramites y requisitos'},
        ),
        migrations.RenameField(
            model_name='tramite_requisito',
            old_name='requisito_id',
            new_name='requisito',
        ),
        migrations.RenameField(
            model_name='tramite_requisito',
            old_name='tipo_tramite_id',
            new_name='tipo de tramite',
        ),
    ]
