# Generated by Django 3.2.12 on 2022-12-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0006_auto_20221220_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimientotramite',
            old_name='area_derivacion_id',
            new_name='area_derivacion',
        ),
        migrations.RenameField(
            model_name='seguimientotramite',
            old_name='tramite_id',
            new_name='tramite',
        ),
        migrations.RenameField(
            model_name='tramite',
            old_name='persona_id',
            new_name='persona',
        ),
    ]
