# Generated by Django 3.2.12 on 2022-12-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0007_auto_20221220_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite_requisito',
            old_name='tipo de tramite',
            new_name='tipo_de_tramite',
        ),
    ]
