# Generated by Django 3.2.12 on 2022-12-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0008_rename_tipo de tramite_tramite_requisito_tipo_de_tramite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='tipo de tramite',
            new_name='tipo_de_tramite',
        ),
    ]
