# Generated by Django 3.2.12 on 2022-12-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cargoarea_grado_academico'),
        ('mesa_partes', '0009_rename_tipo de tramite_tramite_tipo_de_tramite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='tipo_de_tramite',
            new_name='tipo_tramite',
        ),
        migrations.AlterField(
            model_name='seguimientotramite',
            name='area_derivacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='area de derivacion'),
        ),
    ]
