# Generated by Django 3.2.12 on 2022-12-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0010_auto_20221220_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite_requisito',
            old_name='tipo_de_tramite',
            new_name='tipo_tramite',
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.tipotramite', verbose_name='tipo de tramite'),
        ),
    ]
