# Generated by Django 3.2.12 on 2022-12-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cargoarea_grado_academico'),
        ('mesa_partes', '0011_auto_20221220_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='area_derivacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='area de derivacion'),
        ),
        migrations.AlterField(
            model_name='tramite_requisito',
            name='tipo_tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.tipotramite', verbose_name='tipo de tramite'),
        ),
    ]
