# Generated by Django 3.2.12 on 2022-12-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0012_auto_20221221_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='area_derivacion',
        ),
    ]
