# Generated by Django 3.2.12 on 2022-12-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cargoarea_grado_academico'),
        ('mesa_partes', '0013_remove_tramite_area_derivacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientotramite',
            name='area_derivacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='area de derivacion'),
        ),
    ]
