# Generated by Django 3.2.12 on 2022-12-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0014_alter_seguimientotramite_area_derivacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('is_activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'expediente',
                'verbose_name_plural': 'expedientes',
            },
        ),
        migrations.AlterModelOptions(
            name='seguimientotramite',
            options={'verbose_name_plural': 'seguimiento de los tramites'},
        ),
        migrations.AlterField(
            model_name='seguimientotramite',
            name='is_iniciado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tramite',
            name='expediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mesa_partes.expediente'),
            preserve_default=False,
        ),
    ]
