# Generated by Django 3.2.12 on 2022-12-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0015_auto_20221228_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='asunto',
            field=models.TextField(default=''),
        ),
    ]
