# Generated by Django 3.2.12 on 2022-12-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0016_expediente_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientotramite',
            name='accion',
            field=models.CharField(default='', max_length=250),
        ),
    ]
