# Generated by Django 3.2.12 on 2023-01-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0018_alter_tramite_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='documento_identidad',
            new_name='num_documento',
        ),
        migrations.RenameField(
            model_name='tramite',
            old_name='persona_nombre',
            new_name='persona_entidad',
        ),
        migrations.AddField(
            model_name='tramite',
            name='num_doc_referencia',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='asunto',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
