# Generated by Django 3.2.12 on 2022-03-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('academicos', '0003_alter_programa_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicos.programa')),
            ],
        ),
    ]
