# Generated by Django 3.2.12 on 2022-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='promocion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
