# Generated by Django 3.2.12 on 2022-05-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0002_expediente_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
