# Generated by Django 3.2.12 on 2022-05-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0003_expediente_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
