# Generated by Django 3.2.12 on 2022-08-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0004_alter_expediente_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='is_retired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
