# Generated by Django 3.2.12 on 2022-10-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0005_expediente_is_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='res_dir_ingreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='res_rec_ingreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
