# Generated by Django 3.2.12 on 2022-10-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0006_auto_20221006_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='res_dir_ingreso',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='res_rec_ingreso',
        ),
        migrations.AddField(
            model_name='expediente',
            name='res_dirc_ingreso',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='res_rect_ingreso',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
