# Generated by Django 3.2.12 on 2022-10-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0007_auto_20221006_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='is_graduate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
