# Generated by Django 3.2.12 on 2022-10-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_persona_celular'),
        ('admision', '0008_expediente_is_graduate'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.periodo'),
        ),
    ]
