# Generated by Django 3.2.12 on 2023-07-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0009_expediente_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='res_dirc_reingreso',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
