# Generated by Django 3.2.12 on 2023-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0010_expediente_res_dirc_reingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='res_dir_retiro',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
