# Generated by Django 3.2.12 on 2023-10-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0011_expediente_res_dir_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='codigo_universitario',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
